[build]
  publish = "/"
  command = ""  # No build command needed for static site

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"

# Handle SPA routing
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 