[build]
  publish = "frontend"
  command = "# no build command needed"

[[redirects]]
  from = "/api/*"
  to = "https://shadow-zone-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Handle SPA routing
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 